name: epub-metadata

on:
  pull_request:
    branches:
      - main
      - production

jobs:
  run_test:
    name: Run Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest build twine
        if [ -f requirements.txt ];
          then pip install -r requirements.txt;
        fi
    - name: Test with pytest
      run: |
        python -m pytest
  build:
    name: Build and Upload to PyPi
    if: github.event_name == 'pull_request' && github.base_ref == 'production'
    needs: run_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest build twine
        if [ -f requirements.txt ];
          then pip install -r requirements.txt;
        fi
    - name: Build epub-metadata package
      run: |
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
